@echo off
echo Setting up virtual environment ...
python -m venv venv
echo Installing requirements ...
.\venv\Scripts\pip install -r requirements.txt cx_Freeze
echo Building binaries ...
start .\venv\Scripts\cxfreeze -c run_seekers.py --target-dir dist/seekers --include-files config.ini
start .\venv\Scripts\cxfreeze -c run_client.py --target-dir dist/client