# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import seekers_pb2 as seekers__pb2


class SeekersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/world.Seekers/Join',
                request_serializer=seekers__pb2.JoinRequest.SerializeToString,
                response_deserializer=seekers__pb2.JoinReply.FromString,
                )
        self.Properties = channel.unary_unary(
                '/world.Seekers/Properties',
                request_serializer=seekers__pb2.PropertiesRequest.SerializeToString,
                response_deserializer=seekers__pb2.PropertiesReply.FromString,
                )
        self.Status = channel.unary_unary(
                '/world.Seekers/Status',
                request_serializer=seekers__pb2.StatusRequest.SerializeToString,
                response_deserializer=seekers__pb2.StatusReply.FromString,
                )
        self.Command = channel.unary_unary(
                '/world.Seekers/Command',
                request_serializer=seekers__pb2.CommandRequest.SerializeToString,
                response_deserializer=seekers__pb2.CommandReply.FromString,
                )


class SeekersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Properties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeekersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=seekers__pb2.JoinRequest.FromString,
                    response_serializer=seekers__pb2.JoinReply.SerializeToString,
            ),
            'Properties': grpc.unary_unary_rpc_method_handler(
                    servicer.Properties,
                    request_deserializer=seekers__pb2.PropertiesRequest.FromString,
                    response_serializer=seekers__pb2.PropertiesReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=seekers__pb2.StatusRequest.FromString,
                    response_serializer=seekers__pb2.StatusReply.SerializeToString,
            ),
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=seekers__pb2.CommandRequest.FromString,
                    response_serializer=seekers__pb2.CommandReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.Seekers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Seekers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/world.Seekers/Join',
            seekers__pb2.JoinRequest.SerializeToString,
            seekers__pb2.JoinReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Properties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/world.Seekers/Properties',
            seekers__pb2.PropertiesRequest.SerializeToString,
            seekers__pb2.PropertiesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/world.Seekers/Status',
            seekers__pb2.StatusRequest.SerializeToString,
            seekers__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/world.Seekers/Command',
            seekers__pb2.CommandRequest.SerializeToString,
            seekers__pb2.CommandReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
